-- EJECUTA TODO ESTE ARCHIVO EN SUPABASE > SQL EDITOR

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text default 'Bocadillo',
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.extras (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.order_windows (
  id bigint generated by default as identity primary key,
  open boolean not null default false,
  closes_at timestamptz not null,
  opened_by uuid references public.profiles(id),
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id),
  order_window_id bigint references public.order_windows(id),
  menu_item_id bigint references public.menu_items(id),
  extra_ids bigint[] default '{}',
  total numeric(10,2) not null,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.menu_items enable row level security;
alter table public.extras enable row level security;
alter table public.order_windows enable row level security;
alter table public.orders enable row level security;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;

drop policy if exists "profiles read" on public.profiles;
create policy "profiles read" on public.profiles for select to authenticated using (true);

drop policy if exists "profiles admin all" on public.profiles;
create policy "profiles admin all" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "menu public read" on public.menu_items;
create policy "menu public read" on public.menu_items for select to authenticated using (true);
drop policy if exists "menu admin write" on public.menu_items;
create policy "menu admin write" on public.menu_items for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "extras public read" on public.extras;
create policy "extras public read" on public.extras for select to authenticated using (true);
drop policy if exists "extras admin write" on public.extras;
create policy "extras admin write" on public.extras for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "windows read" on public.order_windows;
create policy "windows read" on public.order_windows for select to authenticated using (true);
drop policy if exists "windows admin write" on public.order_windows;
create policy "windows admin write" on public.order_windows for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "orders own read" on public.orders;
create policy "orders own read" on public.orders for select to authenticated using (user_id=auth.uid() or public.is_admin());
drop policy if exists "orders own insert" on public.orders;
create policy "orders own insert" on public.orders for insert to authenticated with check (user_id=auth.uid());
drop policy if exists "orders admin write" on public.orders;
create policy "orders admin write" on public.orders for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Estadísticas: lectura de pedidos para todos los usuarios autenticados.
-- Si quieres que las estadísticas sean visibles incluso sin iniciar sesión,
-- cambia posteriormente esta política a "to anon, authenticated".
drop policy if exists "stats read" on public.orders;
create policy "stats read" on public.orders for select to authenticated using (true);

-- Datos iniciales de ejemplo
insert into public.menu_items (name,category,price) values
('Tortilla','Bocadillo',4.00),
('Jamón','Bocadillo',4.50),
('Bacon','Bocadillo',4.50)
on conflict do nothing;

insert into public.extras (name,price) values
('Agua',1.00),
('Coca-Cola',1.50),
('Café',1.20)
on conflict do nothing;
